### ISSUE TITLE
Erro na Spartana Cadastro completo

### ISSUE THREAD

**Issue by diegorojas** [brasadesign/spts-theme#10]
No debug mode ligado temos o seguinte erro impresso logo no começo do cadastro:
Notice: Undefined offset: 0 in /var/www/html/.../spartanas-cadastro-completo.php on line 22

**Comment by diegorojas** [comment]
Recebi informações da ultima Dev e ela disse que os cadastro usam um Plugin: Profile Builder Pro. Talvez essa issue tenha a ver com isso. Ele esta no repositório em versão gratuita: https://wordpress.org/plugins/profile-builder/

**Comment by diegorojas** [comment]
Voltamos ao erro

**Comment by LuwkasLima** [comment]
This issue was moved to LuwkasLima/Issues_Test#37
