### ISSUE TITLE
Implementar Opções para colocar dois links nas laterais do background

### ISSUE THREAD

**Issue by diegorojas** [brasadesign/spts-theme#11]
Existem dois banners no background do site que sao links para Spartanas. Precisamos colocar esse dois campos em Opções. Campo de URL do banner da esquerda e da direita.

Pode ser tb na aba de Opções "Banners" que citei na issue #4

Substituir nos header.php o codigo feito na mao pela chamada via Opções.

**Comment by LuwkasLima** [comment]
This issue was moved to LuwkasLima/Issues_Test#36
