### ISSUE TITLE
Implementar Opções para substituir sidebar Banners Rodape

### ISSUE THREAD

**Issue by diegorojas** [brasadesign/spts-theme#12]
Existe uma sidebar para gerenciar o iframe que esta na parte inferior do site. 

![Uploading substituir-banner-rodape.png . . .]()

Substituir somando mais um campo na aba Banners de Opções, Banner Rodape.

**Comment by LuwkasLima** [comment]
This issue was moved to LuwkasLima/Issues_Test#35
