### ISSUE TITLE
Criar botão (action) de duplicar Anúncio

### ISSUE THREAD

**Issue by diegorojas** [brasadesign/spts-theme#17]
Criar um botão "Duplicar Anúncio" abaixo de Detalhes do Anuncio:

![detalhes](https://cloud.githubusercontent.com/assets/3632627/6694877/dcefcd92-ccbb-11e4-9adb-6037bb5a0bff.png)

Ou em um toggle novo ou abaixo de Observações dependendo de como vai resolver isso. Acho que a action deve duplicar o Type no banco adicionando ou -2 ou -3 depois tanto do Slug (padrão do WP)  como também do Título para facilitar para o usuário final.

**Comment by diegorojas** [comment]
Foi muito simples de resolver com o Plugin:
https://wordpress.org/plugins/post-duplicator/

O Matheus achou o seguinte código, que ainda pode ser bem util, e estou documentando:
http://rudrastyh.com/wordpress/duplicate-post.html

**Comment by diegorojas** [comment]
O cliente achou demais tudo poder ficar duplicável, que é o que o plugin faz. Podemos usar aquela classe que tinha achado e colocar o botão de duplicar só em "Anúncios"?

**Comment by diegorojas** [comment]
Pode ser na Lista de posts mesmo, como o plugin e a classe fazem.

**Comment by matheusgimenez** [comment]
feito no ultimo commit

**Comment by diegorojas** [comment]
Matheus, veja a possibilidade de aplicar o botão de duplicar na lista de anuncios que há no editar do perfil Spartana:

![Uploading anucios-em-spartanas.png…]()

**Comment by LuwkasLima** [comment]
This issue was moved to LuwkasLima/Issues_Test#30
