### ISSUE TITLE
Colocar Coluna com a contagem de visitas em Spartanas >> Dashboard

### ISSUE THREAD

**Issue by diegorojas** [brasadesign/spts-theme#19]
Colocar essa visualização, conforme havia no plugin usado anteriormente, em produção está assim: 

![pots-views-count](https://cloud.githubusercontent.com/assets/3632627/6901356/fc93327a-d6e2-11e4-8251-020df56db8f4.png)

Qualquer coisa parecida com isso está ótima :)

**Comment by LuwkasLima** [comment]
This issue was moved to LuwkasLima/Issues_Test#28
