### ISSUE TITLE
Novos botões Header para opções

### ISSUE THREAD

**Issue by diegorojas** [brasadesign/spts-theme#21]
Criar as opções para colocar as 4 URLS do novos botões e as condicionais para sumirem quando não houver preenchimento.

![novos-botoes](https://cloud.githubusercontent.com/assets/3632627/7009065/15a1d024-dc6e-11e4-88fa-7b52d6bdf41d.png)

Em uma nova aba  do "Opções do tema" >> Header

**Comment by matheusgimenez** [comment]
feito no ultimo issue

**Comment by LuwkasLima** [comment]
This issue was moved to LuwkasLima/Issues_Test#25
