### ISSUE TITLE
Condicionais na nova Topbar

### ISSUE THREAD

**Issue by diegorojas** [brasadesign/spts-theme#22]
Na nova barra do topo para login, deixei coisa sobrepostas, que precisam de condicionais.

Se a pessoa não estiver logada deve ver:

![top-bar-deslogado](https://cloud.githubusercontent.com/assets/3632627/7009256/61196eee-dc6f-11e4-84cc-0486c745d9fd.png)

Se a pessoa estiver logada como Spartana ou Guerreiro deve ver algo assim:

![topbar-logado](https://cloud.githubusercontent.com/assets/3632627/7009271/7da1179c-dc6f-11e4-8cea-74d915dcaae5.png)

(essa condicional ta lá - cada tipo de usuário tem um menu, vai ver no código.)

Mas em uma linha só.

Por ultimo se estiver logado sendo Admin, Editor, Autor deve ver:

![topbar-admin-logado](https://cloud.githubusercontent.com/assets/3632627/7009443/a7e1c42e-dc70-11e4-9b3e-ca735d0755f5.png)

**Comment by matheusgimenez** [comment]
feito no ultimo commit

**Comment by diegorojas** [comment]
Cara.. testa para Editor e Admin ai.. 

Admin fica assim, com os dois menus:
![condicional-admin](https://cloud.githubusercontent.com/assets/3632627/7098376/18b0d350-dfb6-11e4-9c46-2c4456be8250.png)

E aditor sem botão nenhum:
![condicional-editor](https://cloud.githubusercontent.com/assets/3632627/7098379/1ce50270-dfb6-11e4-85a3-e6e175ebc293.png)

Dá uma olhada?

**Comment by diegorojas** [comment]
Matheus, pelo jeito esqueci de uma condicional que é a de Assinante (perfil de usuário). Precisa ter pelo menos um botão de "Sair" na barra.

![topbar-assinante](https://cloud.githubusercontent.com/assets/3632627/7136558/6c02c908-e288-11e4-8509-e15a683f8be4.png)

**Comment by diegorojas** [comment]
Agora é esse Premium Premium que precisa de um menu, com o "Sair" no TopBar, consegue ver?

**Comment by diegorojas** [comment]
@matheusgimenez sobrou um outro pelo aqui.. quando o Guerreiro está ticado como "premium o menu do topo dele fica zerado:

![top-bar-sem-menu](https://cloud.githubusercontent.com/assets/3632627/7432192/54834830-effc-11e4-8361-5f8a1a843c8c.png)

Num ta chamando o menu "Guerreiro", se eu destico o "Premium" fica normal:

![top-bar-desticado](https://cloud.githubusercontent.com/assets/3632627/7432199/62bd82c6-effc-11e4-97dc-8c35b30ab436.png)

**Comment by diegorojas** [comment]
oi @matheusgimenez o cliente percebeu aquelas pequenas falhas que acontecem depois do redirect na top bar... veja a msg dele.. 

![atualizacao-charlotte](https://cloud.githubusercontent.com/assets/3632627/7935360/c30bb58a-0906-11e5-8b68-a2fda49b735a.png)

Pode rever isso? Parece que os headers estao iguais, talvez precisemos de alguma solucao AJAX.. num sei.

**Comment by diegorojas** [comment]
Aqui não achou nada mesmo?

**Comment by LuwkasLima** [comment]
This issue was moved to LuwkasLima/Issues_Test#24
