### ISSUE TITLE
Implementar Opções para substituir sidebar Anuncio Horizontal

### ISSUE THREAD

**Issue by diegorojas** [brasadesign/spts-theme#23]
Existe um outro banner que aparece no header abaixo dos 6 banner quadrados que você já tornou opção:

![anuncio-horizontal](https://cloud.githubusercontent.com/assets/3632627/7009696/7b23fc3e-dc72-11e4-9d2d-2dffb014d73d.png)

As dimensões desse banner são: 728 x 90 pixels, depois pode apagar a sidebar correspondente.

**Comment by matheusgimenez** [comment]
feito no ultimo commit

**Comment by LuwkasLima** [comment]
This issue was moved to LuwkasLima/Issues_Test#23
