### ISSUE TITLE
Controle de Período de exibição para Banners + controle _self/_blank

### ISSUE THREAD

**Issue by diegorojas** [brasadesign/spts-theme#27]
O cliente está solicitando uma adição de opções para setar período em que os banners serão exibidos. Um para cada um. 

Também gostaria de somar um select em cada link para escolher entre link _self ou link _blank.

![banners-para-controlar](https://cloud.githubusercontent.com/assets/3632627/7244920/6792e5d4-e7b9-11e4-9628-52350c336ab6.png)

**Comment by diegorojas** [comment]
Matheus, para você entender porque está aberto isso aqui. O controle de banners precisava de campos para data de inicio de exibição também. 

Precisam também da opção para definir se o target do link será _self ou _blank

**Comment by matheusgimenez** [comment]
feito no ultimo commit

**Comment by LuwkasLima** [comment]
This issue was moved to LuwkasLima/Issues_Test#19
