### ISSUE TITLE
Prioridade 1 - Criar um Menu e aplicar na listagem de sites da barra no topo

### ISSUE THREAD

**Issue by diegorojas** [brasadesign/spts-theme#28]
Matheus, o cliente que deixar o uso do plugin que fez para depois :(

Como ele faz parceria com dois site que não serão subsites em primeiro momento ele queria um menu administrável pelos Menus do admin mesmo, o local no front é esse aqui:

![menu-cidades](https://cloud.githubusercontent.com/assets/3632627/7432458/a5721f58-effe-11e4-9242-0e059c5cd025.png)

**Comment by diegorojas** [comment]
@matheusgimenez o menu foi criado mas ainda não está chamando no lugar da listagem.

**Comment by matheusgimenez** [comment]
feito no ultimo commit

**Comment by LuwkasLima** [comment]
This issue was moved to LuwkasLima/Issues_Test#18
