### ISSUE TITLE
Reforma na Busca com Filtro de Taxonomia

### ISSUE THREAD

**Issue by diegorojas** [brasadesign/spts-theme#29]
Aqui a coisa é aplicar novos campos e filtros conforme a imagem

![nova-busca-filtrada](https://cloud.githubusercontent.com/assets/3632627/7497132/0102cf9a-f3ef-11e4-804c-4b92deaf3ba9.jpg)

e o PSD que está no Drive, envio link pelo telegram

**Comment by diegorojas** [comment]
pasta >> LAYOUTS NOVOS

**Comment by diegorojas** [comment]
Precisamos de mais um detalhe aqui. A quantidade de resultado do query está batendo com o numero de posts setado no painel, 10. Como existem resultados de busca com mais de 10 deusas, seria necessário exibirem sempre todos os resultados, o tal "-1".

**Comment by matheusgimenez** [comment]
feito no ultimo commit

**Comment by LuwkasLima** [comment]
This issue was moved to LuwkasLima/Issues_Test#17
