### ISSUE TITLE
Tornar a imagem de Introdução editavel pelas Opções do Tema

### ISSUE THREAD

**Issue by diegorojas** [brasadesign/spts-theme#30]
Criar opção para subir a imagem de intro conforme abaixo:

![bg-intro](https://cloud.githubusercontent.com/assets/3632627/7497243/a83f5b8e-f3ef-11e4-99f8-5d118b7d25f4.jpg)

A dimensão da imagem é de 1109 x 581 pixels

**Comment by matheusgimenez** [comment]
feito no ultimo commit

**Comment by LuwkasLima** [comment]
This issue was moved to LuwkasLima/Issues_Test#16
