### ISSUE TITLE
Prioridade 3 - Deusa ao se logar não consegue mais editar seu perfil;

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/spts-theme#32]
@matheusgimenez as meninas ao se logar não conseguem editar seu perfil:

"Eu tentei terminar de editar meu perfil hoje mais não estou conseguindo.
Clico em alterar perfil e o papiro aparece branco."

A Pagina de edicao de perfil utiliza o shortcode do Contact Form 7. Existe um shortcode (dentro do contact form chamado "Cadastro Completo Spartana (editar)") que eh utilizado pra buscar a informacao do usuario e popular o formulario: [dynamichidden profileid id:profileid "profileid"]

Hoje, quando entramos na pagina de edicao do perfil (form) ela aparece assim:

Pagina: http://spartanasbrasilia.com.br/editar-cadastro/

![image](https://cloud.githubusercontent.com/assets/5949986/7522076/6c1a287c-f4b8-11e4-8801-786e95f1b459.png)

Quando retiramos o shortcode ([dynamichidden profileid id:profileid "profileid"]) o formulario aparece mas sem dados:

![image](https://cloud.githubusercontent.com/assets/5949986/7522109/aee9ea52-f4b8-11e4-9470-3d0bcc822177.png)

Precisamos descobrir como trazer os dados do formulario que esta vinculado ao perfil da Deusa.

**Comment by LuwkasLima** [comment]
Adiocionando aqui mais detalhes do teste:

A Spartana (Role) faz login e clica em Alterar Cadastro/Perfil e eh direcionada pra pagina http://spartanasbrasilia.com.br/alterar-cadastro/

![image](https://cloud.githubusercontent.com/assets/5949986/7523506/d13415b6-f4c1-11e4-972f-d4dda778e5ce.png)

Assim que voce modifica os campos e clica em Enviar, aparece o "reloginho" e nao sai disso:

![image](https://cloud.githubusercontent.com/assets/5949986/7523453/7536b6b0-f4c1-11e4-94a6-f6ed0aecc401.png)

**Comment by LuwkasLima** [comment]
O formulario eh inserido em branco:

![image](https://cloud.githubusercontent.com/assets/5949986/7523664/aec14bd8-f4c2-11e4-802e-820ea293c9fe.png)

**Comment by diegorojas** [comment]
@matheusgimenez e @LuwkasLima vamos se concentrar nessa aqui, a outra é uma sub tarefa dessa. O erro de brasilia aconteceu porque eu coloquei o template errado mesmo... mas depois explico, o alterar cadastro se comporta como cadastro completo quando alguem que só fez o cadastro preliminar vai em Alterar Perfil...

**Comment by LuwkasLima** [comment]
This issue was moved to LuwkasLima/Issues_Test#14
