### ISSUE TITLE
Não exibir qualquer Anuncio de qq Spartana que estiver setada como Rascunho no FrontEnd

### ISSUE THREAD

**Issue by diegorojas** [brasadesign/spts-theme#35]
Aplicar nos querys do site uma relação com o post status da deusa. Qualquer Anuncio no FrontEnd de alguma Deusa que estiver com rascunho, não deve aparecer.

**Comment by diegorojas** [comment]
@matheusgimenez testei agora e tentei colocar em produção em brasilia, não ta rolando.. Os anuncios de uma Spartana em rascunho como o Arena e o Destaque continuam aparecendo.. :(

**Comment by matheusgimenez** [comment]
feito no ultimo commit

**Comment by LuwkasLima** [comment]
This issue was moved to LuwkasLima/Issues_Test#11
