### ISSUE TITLE
Duas Opções de Video para Home

### ISSUE THREAD

**Issue by diegorojas** [brasadesign/spts-theme#36]
Areas fixas de Clip Sensual e Entrevista entre Vitrines e Busca Filtrada.

![destaques na home](https://cloud.githubusercontent.com/assets/3632627/7812905/b2cbd1d4-038c-11e5-86ea-93ac01141eba.png)

Opções serão:

- Shortcode do video
- Titutlo do video
- Descrição do Video

Se não estiver setado não aparece.

**Comment by LuwkasLima** [comment]
This issue was moved to LuwkasLima/Issues_Test#10
