### ISSUE TITLE
Rever retirada de Minhas favoritas "live"

### ISSUE THREAD

**Issue by diegorojas** [brasadesign/spts-theme#41]
O clicar em "Favorita!(remover)" na page-minhas-favoritas.php está sumindo localmente na hora mas não no site em produção, precisa recarregar a pagina para ver que foi retiradada

Aparece um pequenos erro via Console que não sei se têm a ver:
```
TypeError: a.replace is not a function
```

**Comment by diegorojas** [comment]
Matheus, dá uma olhada nisso por favor? Parece que num tá rolando mais nem em produção e nem local aqui :( achei que era a tal da classe delfavaction mas parece que num tá rolando

**Comment by LuwkasLima** [comment]
This issue was moved to LuwkasLima/Issues_Test#4
