### ISSUE TITLE
Minhas Favoritas >> Erro na exibição de posts no query

### ISSUE THREAD

**Issue by diegorojas** [brasadesign/spts-theme#43]
Seguinte matheus, hoje testando em MultiSite adicionando favoritas em São Paulo e Brasilia, veja a tela que eu cai, tá caindo uns posts bizarros no query. Acha que tem alguma forma de contornar isso?

![bug-query-minhas-favoritas](https://cloud.githubusercontent.com/assets/3632627/8208294/4688240c-14dd-11e5-968e-c6f424948cf2.png)

**Comment by LuwkasLima** [comment]
This issue was moved to LuwkasLima/Issues_Test#3
