### ISSUE TITLE
Substituir plugin Option Tree por Opções - Background

### ISSUE THREAD

**Issue by diegorojas** [brasadesign/spts-theme#6]
Implementar a atual opção de subir Background do plugin no "Aparência" do tema na opção nativa "Fundo", usado no twentytwelve por exemplo, base desse tema aqui.

No site em produção temos o seguinte:
![background](https://cloud.githubusercontent.com/assets/3632627/6493632/c1ecbe2c-c29a-11e4-8e08-306e7f6f42db.png)

Mas não precisa ficar igual, só ter a mesma funcionalidade. Depois de feito isso precisa substituir o atual script ot_get_option() espalhado pelos templates.

**Comment by diegorojas** [comment]
@matheusgimenez o cliente se atrapalhou com a solução do custom background separado do lugar onde coloca os links para o background. Vamos fazer esse background como uma Opção do Tema e não mais usado o "Custo Header" do wp, ok?

**Comment by matheusgimenez** [comment]
Ok

**Comment by matheusgimenez** [comment]
feito no ultimo commit

**Comment by diegorojas** [comment]
Cara, aqui vamos precisa de um controle de datas tambem, igual ao slider.

**Comment by matheusgimenez** [comment]
feito no ultimo commit

**Comment by LuwkasLima** [comment]
This issue was moved to LuwkasLima/Issues_Test#41
