### ISSUE TITLE
Remover acesso ao dashboard de alguns grupos de usuários

### ISSUE THREAD

**Issue by diegorojas** [brasadesign/spts-theme#7]
Colocar isso no functions para podermos retirar o plugin Remove Dashboard Access, e também retirarmos outros plugins como o Profile Editor e o User Role Editor. Precisamos chegar na seguinte tabela de quem pode e quem não pode acessar o dashboard:

![capabilities-de-usuarios](https://cloud.githubusercontent.com/assets/3632627/6494800/01e1b548-c2a3-11e4-8a3e-7c44b6ab7734.png)

Não precisa ter tela de opção. Redirecionar o visitante que não tiver acesso para a URL - home_url/home

**Comment by matheusgimenez** [comment]
feito no ultimo commit

**Comment by matheusgimenez** [comment]
dei uma organizada melhor no codigo nesse ultimo commit

**Comment by diegorojas** [comment]
Matheus, preciso de um redirect para esse grupos de usuários que não tem acesso ao dashboard. Todos devem ser redirecionados para a home_url('/home')

**Comment by matheusgimenez** [comment]
Já fiz nao fiz?

**Comment by matheusgimenez** [comment]
Ah saquei.. ta indo para página inicial e vc quer /home né?

**Comment by diegorojas** [comment]
isso! :)

**Comment by matheusgimenez** [comment]
feito no ultimo commit

**Comment by LuwkasLima** [comment]
This issue was moved to LuwkasLima/Issues_Test#40
