### ISSUE TITLE
Adicionar ao Editor a capacidade de mexer em Widgets, Menus e Opções

### ISSUE THREAD

**Issue by diegorojas** [brasadesign/spts-theme#8]
Implementar no functions com uma capabilitie do grupo de usuários - Editor

**Comment by diegorojas** [comment]
@matheusgimenez chegou a fazer isso aqui?

**Comment by matheusgimenez** [comment]
Deixei passar, sorry.. faço hoje

**Comment by matheusgimenez** [comment]
feito no ultimo commit

**Comment by diegorojas** [comment]
@matheusgimenez desculpe mas precisamos de uma extensão disso aqui, o Editor também não deve ver no men: "Configurações"; "Contact Form DB", "Tipos".

Estranho Configurações estarem aparecendo para Editores não?

**Comment by diegorojas** [comment]
Fiquei intrigado com essa tabela aqui:

![tabela-capabilities](https://cloud.githubusercontent.com/assets/3632627/6905538/fab97768-d6fe-11e4-81fa-ae10a3739650.png)

Capaz do Types estar mexendo nas capabilities tb?

**Comment by matheusgimenez** [comment]
Provavelmente

**Comment by diegorojas** [comment]
Certo, bom, já vi que precisa pegar um addon para gerenciar isso :(

Por hora dá para tirar na marra o Configurações dos Editores?

**Comment by diegorojas** [comment]
Isso aqui fica parado por enquanto, nos deram autorização para comprar o addon do Types lá que gerencia isso, vamos ver se com ele resolvemos tudo.

**Comment by LuwkasLima** [comment]
This issue was moved to LuwkasLima/Issues_Test#39
